### ISSUE TITLE
Small typo in our README

### ISSUE THREAD

**Issue by pcloup** [F5Networks/f5-google-gdm-templates#11]
## Description
The reference to ARM templates in GDM templates is a typo or copy/paste issue. It should be GDM instead of ARM.
see the supported/standalone/1nic/existing-stack/payg/README.md for example

- All supported versions of F5 **ARM** templates now include Application Services 3 Extension (AS3) v3.5.1 (LTS version) on the BIG-IP VE.  AS3 uses a declarative configuration model, meaning you send a declaration file using a single Rest API call. See the [AS3 documentation](https://clouddocs.f5.com/products/extensions/f5-appsvcs-extension/3.5.1/) for details on how to use AS3 on your BIG-IP VE(s).

**Comment by f5-gasingh** [comment]
Captured this bug and tracking this issue internally with id -866. Thanks.

**Comment by crosbygw** [comment]
Doc correction issued in [v2.1.1](https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v2.1.1)
