### ISSUE TITLE
incorrect 3-NIC cluster reference

### ISSUE THREAD

**Issue by pcloup** [F5Networks/f5-google-gdm-templates#12]
## Description
In our README page (https://github.com/F5Networks/f5-google-gdm-templates/README.md), we reference a "Clustered BIG-IP VE - 3 NICs" which in reality points to a single NIC template, which is incorrect and confusing our customers.

**Comment by f5-gasingh** [comment]
Thank you for catching that. I've created a issue for this in our internal tool and are tracking with id -865

**Comment by crosbygw** [comment]
Document correct issued with release [v2.1.3](https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v2.1.3)
