### ISSUE TITLE
API Failover doesnt work with Custom DNS

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-google-gdm-templates#14]
## Description

Using custom DNS in the BIG-IP will cause the failover to fail to work, if you need logs please let me know (this can be provided internally)

Steps to reproduce:

If I add my own DNS servers under sys/dns it no longer fails over (unless I have the default DNS server listed first)
If I revert the changes it will failover again fine.

## Template
[PAYG Template](https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/failover/same-net/via-api/3nic/existing-stack/payg)

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity:
3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.

**Comment by edwoodjrjr** [comment]
Hi Jon, tracking this with internal issue #904.

**Comment by garrettdieckmann** [comment]
Hello Jon,

Release v2.2.0 (released May 7th) included a fix for this issue (internal issue #904). Our Failover templates now adds a host route to the hostname of Google's metadata service (metadata.google.internal).
