### ISSUE TITLE
when deploying cluster template and using service discovery, service account requires access to storage bucket

### ISSUE THREAD

**Issue by assareh** [F5Networks/f5-google-gdm-templates#17]
## Description
when deploying a cluster template, if I populate the serviceAccount label with my service account so I can use the service discovery feature, the BIG-IP devices don't form a cluster and I see the following error in /var/log/cloud/google/cluster.log:

___.gserviceaccount.com does not have storage.objects.get access to f5-bigip-____/credentials/master."

This is resolved by adding additional storage object roles to my service account however this is not documented. 

## Template
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/failover/same-net/via-api/3nic/existing-stack/byol

## Severity Level
5

**Comment by namhly** [comment]
Thanks Andy. We've created a bug ID 1136 for this issue.

**Comment by alaari-f5** [comment]
this is fixed.
