### ISSUE TITLE
3nic supported stack requires 3 google vpc networks...not two

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#2]
Pre-reqs state in the 3nic template that 2 google networks are needed with at least 1 subnet each. This is not correct. You need 3 google networks (VPCs) with at least 1 subnet each. The VM instance in Google can only have one NIC per VPC network.

Please update the pre-reqs and any other mention of similar to reflect needing three instead...

"Two Google Cloud Platform (GCP) networks with at least one subnet in each"

**Comment by f5-gasingh** [comment]
Hello Jeff, we have verified that the 3nic readmes have the updated pre-req you mentioned above. Thank you for reporting.
