### ISSUE TITLE
Add option to add custom 'network tags' on BIG-IP VM instance(s)

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-google-gdm-templates#21]
Network Tags are very handy when creating firewall rules in GCP, having an option to add custom network tags to the created BIG-IP instance(s) would be helpful.

**Comment by f5-gasingh** [comment]
Hi simonkowallik, I've added this enhancement request to our backlog and will be tracking this internally with id -1294. Thank you.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
