### ISSUE TITLE
Startup GDM Template missmatch with YAML template

### ISSUE THREAD

**Issue by cbayonag** [F5Networks/f5-google-gdm-templates#24]
## Do you already have an issue opened with F5 support?
We are working on the lab environment then its going to take a while the case.

## Description
Hello guys just found that the BYOL YAML 3 -NIC for GDM isn't working as expected, the NIC 1 must be the Management in version 2.2.0 and later. But when deployed the bigip boots by first time on NIC 0 as a mgmt interface, after a reboot got the NIC 1 but the bootstrap mgmt-ip stays on NIC0

## Template
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/standalone/3nic/existing-stack/byol

## Severity Level

Severity: 1

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by namhly** [comment]
Hi @cbayonag,
Thank you for reporting this bug. We have opened an internal issue 1408 to track this issue.

**Comment by jsevedge** [comment]
@cbayonag What do you mean by bootstrap mgmt-ip?  What image did you use for the deployment?

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
