### ISSUE TITLE
ASM is not ready. 3NIC standalone PAYG template

### ISSUE THREAD

**Issue by howsTricks** [F5Networks/f5-google-gdm-templates#25]
## Do you already have an issue opened with F5 support?
No

## Description
Deploy 3 NIC standalone PAYG Best template and enable the ASM feature results in the following being displayed in the F5 GUI: ASM is not ready.

ASM is one of the primary reasons to use this image so I would consider this a nonfunctional template until this issue is resolved. 

## Template
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/standalone/3nic/existing-stack/payg

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 1

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by jsevedge** [comment]
@howsTricks What instance size did you use? Does anything stand out in /var/log/*?  Have you opened an F5 support case for this issue?

If the template deployed successfully and there is enough disk size and cores available that message is definitely surprising.

**Comment by howsTricks** [comment]
I just cleared everything out and did a new deploy from scratch and am getting the same thing as before. The only thing I've done is add an ssh key and then enable the ASM feature. The asm log repeatedly shows the following log, but some additional info at the beginning.

Jun 10 08:03:59 bigip1-wln-development-f5deploy err tsconfig.pl[21759]: initial configuration script encountered a fatal error: Failed To Retrive Self Mac Address

Disk usage doesn't appear to be too full, but I'm not an expert at that:

list /sys disk
sys disk logical-disk HD1 {
    mode mixed
    size 83968
    vg-free 22584
    vg-in-use 61156
}
[asm log output.txt](https://github.com/F5Networks/f5-google-gdm-templates/files/3271179/asm.log.output.txt)
[ltm log output.txt](https://github.com/F5Networks/f5-google-gdm-templates/files/3271180/ltm.log.output.txt)

I've attached logs for both ltm and asm log, please take a look and let me know if I'm missing something.

**Comment by jsevedge** [comment]
@howsTricks Will work on reproducing this to see if the template team can provide any helpful solutions.  In the meantime, could you open a case with F5 support as well?  If it ends up being an issue with ASM, etc. that might be a better avenue to get a resolution.

**Comment by howsTricks** [comment]
Since I'm using PAYG I'm not sure how to open tickets with F5 support. Any word on getting this reproduced?

**Comment by jsevedge** [comment]
Ah, I was able to reproduce this and found a known workaround.

BZ ID previously opened: 726401

"As a workaround, the value of "iface0" should be changed to the appropriate interface in /etc/ts/common/image.cfg, as follows:

----------------------------------------------------------------------
[4000]                           
iface0=eth1
iface1=eth1
DefaultHostsFile=/ts/install/hosts.4000
----------------------------------------------------------------------"

**Comment by jsevedge** [comment]
@howsTricks Did you get a chance to test this out and see if it worked for you?

**Comment by howsTricks** [comment]
Hi @jsevedge Sorry, not yet, been quite busy with some other parts of our implementation. I'll check it out as soon as I can. Thanks for the workaround research.

**Comment by net47** [comment]
> Ah, I was able to reproduce this and found a known workaround.
> 
> BZ ID previously opened: 726401
> 
> "As a workaround, the value of "iface0" should be changed to the appropriate interface in /etc/ts/common/image.cfg, as follows:
> 
> [4000]
> iface0=eth1
> iface1=eth1
> DefaultHostsFile=/ts/install/hosts.4000
> ----------------------------------------------------------------------"
> 
> Once that is done, bigstart restart and BIG-IP should show online. Give that a try and report back!

Thanks jsevedge, that did the trick! Bugtracker: https://cdn.f5.com/product/bugtracker/ID726401.html

**Comment by jsevedge** [comment]
Very good, so it appears we can close this out as tracking the fix of this within BIG-IP VE will happen via afore-mentioned ID.  Thanks @net47 for confirming.
