### ISSUE TITLE
new-stack or learning-stack for 3nic failover via-api

### ISSUE THREAD

**Issue by depperson** [F5Networks/f5-google-gdm-templates#28]
## Do you already have an issue opened with F5 support?
I am F5 support. 

## Description
Please create a GDM template that sets up a 3nic BIG-IP with API failover and creates the necessary networking stack.  I'm requesting a "learning-stack" or "new-stack" option instead of only having the "existing-stack".

## Template
f5-google-gdm-templates/supported/failover/same-net/via-api/3nic

## Severity Level
**Severity 5 (Trival)** : Defect is not causing any interruptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Thank you for taking the time to submit this issue to us.

I've gone ahead and created an issue in Jira (#1596) to add this template.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
