### ISSUE TITLE
Known Issue: Issues connecting to mgmt address

### ISSUE THREAD

**Issue by jsevedge** [F5Networks/f5-google-gdm-templates#29]
Known Issue Statement: During automated testing we have recently observed a high rate of failures when deploying the Google Deployment Manager templates. After some analysis it appears to be most closely tied to the version of BIG-IP used combined with certain deployment configurations can result in issues connecting to the BIG-IP mgmt port.

Workaround: Use the latest v2.x tagged version of templates (https://github.com/F5Networks/f5-google-gdm-templates/tree/v2.2.0) with BIG-IP 13.1.

RCA status: ongoing

**Comment by wduongf5** [comment]
Release v3.0.3 resolved this issue.
