### ISSUE TITLE
document update for install steps require PY file too

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#3]
It's not completely clear, so I'm opening an issue on it. The GDM deployment instructions in the repo state to deploy the yaml file. This makes it appear that the user only needs to download the yaml file from the repo. The yaml file however has an include for the "py" file and that file too needs to be downloaded into the same directory. This might not be obvious to all users.

Can you update the "deploying yaml" section to also state the "py" file is also needed in same director.

**Comment by f5-gasingh** [comment]
Hello Jeff, we will work on making the instructions more clear. Thank you.

**Comment by crosbygw** [comment]
Starting in [v1.5.0](https://github.com/F5Networks/f5-google-gdm-templates/tree/v1.5.0), deployment [section](https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/standalone/2nic/existing-stack/byol#deploying-the-template) in readme now include notes regarding python script required to create deployments in gdm.
