### ISSUE TITLE
BIG-IQ License Method for Deployments

### ISSUE THREAD

**Issue by jmcalalang** [F5Networks/f5-google-gdm-templates#30]
## Description
We need a BIG-IQ license method, customers have ELA or Subs and need to license instances without having to use individual reg keys. I understand the requirement for BIG-IQ in GCP, this, however, shouldn't be just GCP specific, they could be hosting BIG-IQ in other locations.

## Template
All

## Severity Level
NA

**Comment by alaari-f5** [comment]
Thank you for raising this request. I created an RFE 1671 for this.

**Comment by curtkersey** [comment]
This feature is requested by a customer with a large GCP deployment.  They really want active/active configuration with autoscale to scale WAF.  Need to pull licenses from BIG-IQ.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
