### ISSUE TITLE
Add option for declarative onboard to template

### ISSUE THREAD

**Issue by ajgerace** [F5Networks/f5-google-gdm-templates#32]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.
Add ability to reference a declarative-onboarding declaration to add objects that template does/cannot.  (ex. license device using load sku, add users, etc..)

**Comment by shyawnkarim** [comment]
Thanks for taking the time to reach out to us with an enhancement request. 

I can definitely see how adding declarative onboarding to templates would be useful and convenient. We've heard this request before and may add this functionality in the future. I'll speak to our engineering team and they'll reach out if they have any other questions.

Again, thanks for your feedback and please reach out if there is anything else that we can help you with.

**Comment by shyawnkarim** [comment]
We have a new project, under development, called [F5 BIG-IP Runtime Init](https://github.com/F5Networks/f5-bigip-runtime-init) that will allow you to do just that. It will allow you to provision a BIG-IP using a template, then installs the Automation Toolchain component (in your case DO), and runs the declaration.
