### ISSUE TITLE
BIG-IP Instance names are hard coded in the template

### ISSUE THREAD

**Issue by irgoncalves** [F5Networks/f5-google-gdm-templates#37]
## Do you already have an issue opened with F5 support?
No

## Description
The current templates have the instance names hard-coded as 'bigip1' and 'bigip2'. This prevents the deployment using Customer's nomenclature standard without modifying the template.

## Template
All templates version 3.2.0, standard and failover, single and multiple NIC

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this issue. I have gone ahead and created Jira issue #1750 to get this changed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
