### ISSUE TITLE
support for START CUSTOM CONFIGURATION

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#4]
I'm scanning the GDM template (yaml) looking for a place to inject TMOS configs like we can in AWS and Azure templates. There is a START CUSTOM CONFIGURATION section in those other cloud configs. I see the same mention of this section in the GDM configs within the python file.

Is it safe to assume this is where users make "custom" configuration changes to the GDM template and still stay within scope of full F5 support? I don't see any mention of customizing the L4-L7 day 0 configs (e.g. via START CUSTOM CONFIGURATION) listed anywhere in the repo.

Please clarify.

**Comment by f5-gasingh** [comment]
Hello, we will confirm and get back to you. Thank you.

**Comment by crosbygw** [comment]
The help section, right below the [security](https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/standalone/2nic/existing-stack/payg#security) section, of every readme mentions custom configuration support. It is as you suspected, you are able to enter custom tmsh/shell commands between the ### START CUSTOM TMSH CONFIGURATION and ### END CUSTOM TMSH CONFIGURATION which is contained with each template (.py file).
