### ISSUE TITLE
Documentation wrong: declarationUrl set to default does not deploy AS3 app

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#40]
## Do you already have an issue opened with F5 support?
No

## Description
The declarationUrl parameter states it is required in the table. It also states you can leave value at 'default' or 'none'. When I leave as 'default' in yaml file, the AS3 app service never deploys.

--snippet from custom-config.log--
2020-01-18T02:40:17.655Z info:  Custom config was not a URL, continuing... 
2020-01-18T02:40:17.658Z info:  /config/cloud/gce/custom-config.sh exited with code 0 
2020-01-18T02:40:17.661Z info:  Custom script finished. 

There seems to be something wrong with the way the PY python file is parsing the value and interpreting 'default' around this code line - https://github.com/F5Networks/f5-google-gdm-templates/blob/002b1f5a481562cd38ea3f0ed40dbf1129d6c798/supported/standalone/3nic/existing-stack/payg/f5-existing-stack-payg-3nic-bigip.py#L311

Based on the github README file, I would expect a sample app to deploy as noted in the README and the YAML file such as...
"If left at default, the recommended F5 WAF configuration will be applied"

The actual results is that AS3 RPM is installed, but no apps are created. Therefore no sample virtual server when value left at 'default'.

## Template
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/standalone/3nic/existing-stack/payg

## Severity Level
3

**Comment by shyawnkarim** [comment]
Thanks for reaching out to us with this issue. I've gone ahead a created Jira issue #1804 to get this fixed.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
