### ISSUE TITLE
Please create BIG-IP Image Map

### ISSUE THREAD

**Issue by jtylershaw** [F5Networks/f5-google-gdm-templates#44]
## Description
Please create an image map for GCP akin to the AWS AMI Map (https://github.com/F5Networks/f5-aws-cloudformation/tree/master/AMI%20Maps).

## Severity Level
Severity: 5

**Comment by shyawnkarim** [comment]
Thanks for reaching out with this request. I've created internal ID ESECLDTPLT-1976 for this.

**Comment by f5-applebaum** [comment]
NOTE: Like Azure, Google uses names which are much easier API to use.

You can find the list of images via:
> gcloud compute images list --project f5-7626-networks-public

vs. CFT which you have to go through hoops. CFT has awful Lambda bandaid to provide this same functionality.

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/walkthrough-custom-resources-lambda-lookup-amiids.html

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
