### ISSUE TITLE
service discovery header section wrong mark up 3nic

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#5]
In the supported 3nic template, the links for service discovery do not work within the page. When you scroll down to the section that should be a header for Service Discovery, it looks like this...

\#\# Service Discovery This Google GDM template supports Service Discovery.

I think the markup is missing two additional ## at the end of the word Service Discovery. As a result, the 1nic and 2nic template look correct, but the 3nic template "Service Discovery" section header is not a header. Please correct formatting.

**Comment by f5-gasingh** [comment]
Hello Jeff, this has already been fixed. Please take a look. Thank you.
