### ISSUE TITLE
Hostname character limitation causes startup-script in metadata to fail

### ISSUE THREAD

**Issue by slidersn21** [F5Networks/f5-google-gdm-templates#53]
## Do you already have an issue opened with F5 support? Yes
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.
65 character limitation on the F5 hostname.  If you have more than 65 characters, the Deployment Manager job will finish and no errors are produced but the startup-script in metadata will error out and the instance will fail to configure using the post-setup scripts.  Perhaps a note or example gcloud create command indicating that a character limitation exists for the hostname.

The hostname is part of the gcloud create script name combined with additional characters such as bigip#+createscriptname+gcpprojectname.internal
Example of a non-offending hostname: bigip1-f5-usc1-nonprod.c.###-network-####.internal
Example of an offending hostname: bigip1-f5-3nic-us-central-1-nonprod-pair.c.###-network-####.internal

## Template
For bugs, enter the template with which you are experiencing issues below.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <5>
Trivial yet will cause new deployments to fail in post-deployment setup with no error logs displayed.

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
What template versions. The 3.4 release should have fixed this.

https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v3.4.0
...related to older github issue sorta https://github.com/F5Networks/f5-google-gdm-templates/issues/38

**Comment by slidersn21** [comment]
Version 3.7
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/failover/same-net/via-api/3nic/existing-stack/payg
.

Case # 1-6546892844

The latest qkviews in that case file show the logs from
cloud/google/install.log and onboarding.log with the hostname being over 65
characters.

Spence

**Comment by slidersn21** [comment]
I also had a syntax error for the timezone.  I specified US\Mountain when
it should be US/Mountain.  This also caused the startup-script in metadata
to fail but I figured that was just my fault.

Sidenote:
When the startup-scripts fail the instance cannot be pinged/ssh'd to
outside of the VPC.

**Comment by shyawnkarim** [comment]
Closing. This issue has been resolved.
