### ISSUE TITLE
Define Static MGMT IPs for 2nic-api deployment

### ISSUE THREAD

**Issue by jbaribeault** [F5Networks/f5-google-gdm-templates#54]
## Do you already have an issue opened with F5 support?
No - this is more of a feature request....

## Description
The standalone templates allow the definition of a static MGMT IP - the 2nic API one doesn't.
I realize this is likely due to the first boot behavior requiring internet access from a temporary IP on NIC0 to download requisite code before MGMT being shifted to NIC1....not sure how to fix that as I don't fully grasp the order of operations on that process (still studying the scripts)

## Template
/supported/failover/same-net/via-api/2nic/existing-stack/byol/
v3.4.3

## Severity Level

Severity: 5
Really 6 ;)

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.
 6. Feature request that may be impossible.

**Comment by shyawnkarim** [comment]
Thanks for reaching out with this enhancement request. We are now tracking this issue internally with ESECLDTPLT-2250.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
