### ISSUE TITLE
"Optional" value should be defaulted to working value

### ISSUE THREAD

**Issue by skko29** [F5Networks/f5-google-gdm-templates#55]
## Description

The "Optional" values should default to the value that will work. For instance, 'timezone'  should be replaced with 'UTC' in yaml. When it is marked as optional, people may skip and leave the value as is, causing BIG-IP boots up with no initial configurations like self-ips, routes, etc.

## Template
For bugs, enter the template with which you are experiencing issues below.
I ran into this issue in 'via-api/payg-3nic' template. But suspects it will be the same across all templates.

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 5

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by JeffGiroux** [comment]
For reference, I had to call this out in my article...make sure yaml file is complete. See notes in my article mentioning to make sure ALL parameters are populated and/or commented out.

https://devcentral.f5.com/s/articles/Service-Discovery-in-Google-Cloud-with-F5-BIG-IP

**Comment by shyawnkarim** [comment]
@sankoko29 the template optional values could have working defaults but the default values won't be correct for everyone, especially for the people who are not reading all of the parameter comments in the template. We have made the decision to put them in <> notation so users know they need to fill it in with a working parameter.

**Comment by jtylershaw** [comment]
Hey Shyawn,

San is not the only person who has complained to me about this failure, and
it generally takes an F5 employee who's been through this before to explain
what to do.  Our suggestion is either to comment out the optional values,
or populate them with values that will work.  This is causing customer
confusion.  It's a simple workaround, but it's not an obvious failure that
you can trace back to the optional values being incorrect.  The instances
do not become available with bad NTP server values of <>.  If this were a
simple log file entry on a system that comes up this wouldn't be as big of
an issue for me as it is.

**Comment by shyawnkarim** [comment]
We are now tracking this enhancement internally with internal ID ESECLDTPLT-2249.

**Comment by JeffGiroux** [comment]
Ran into this issue again with another partner. Any updates?

**Comment by shyawnkarim** [comment]
Closing.

This enhancement was included with [Release 3.9](https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v3.9.0).
