### ISSUE TITLE
incorrect compute images in the example YAML

### ISSUE THREAD

**Issue by simonkowallik** [F5Networks/f5-google-gdm-templates#60]
The image in the below yaml doesn't seem to exist in GCP.

https://github.com/F5Networks/f5-google-gdm-templates/blob/3426d8bbe1a0f3045a05701da6c6e0e7293c3ce5/supported/standalone/3nic/existing-stack/byol/f5-existing-stack-byol-3nic-bigip.yaml#L55-L59

Maybe we can also add a hint on how to get the current list:

```sh
gcloud compute images list --project=f5-7626-networks-public
```

**Comment by crosbygw** [comment]
Resolved in release https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v3.11.1
