### ISSUE TITLE
Create Internal Forwarding Rules for Internal VIP using GDM

### ISSUE THREAD

**Issue by densnoigaskogen** [F5Networks/f5-google-gdm-templates#63]
## Do you already have an issue opened with F5 support?
No, not related to this question in subject.

## Description
We have successfully deployed and tested GDM template (byol-3nic-bigip version 3.11.0). The Forwarding rule and VIP was created as external using the template. We also want to create internal VIP, how can we achieve that using GDM template?

## Template
bigip image; f5-bigip-15-1-2-0-0-9-byol-all-modules-2boot-loc-201110230057

## Severity Level
NA

Severity: NA

Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by densnoigaskogen** [comment]
F5 team, can anyone provide a response to the issue, thanks?

**Comment by shyawnkarim** [comment]
For help with template or deployment customization please reach out to F5 Professional Services.

**Comment by shyawnkarim** [comment]
Closing. Please reopen another issue if needed.
