### ISSUE TITLE
post-deployment licensing

### ISSUE THREAD

**Issue by snowblind-** [F5Networks/f5-google-gdm-templates#64]
## Description
Document BIG-IQ post-deployment licensing with unreachable method requiring license generation from the base mac, not the management mac due to mgmt not being on nic0

## Template may affect others
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/supported/failover/same-net/via-api/3nic/existing-stack/byol

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: 3

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking this documentation enhancement with internal ID ESECLDPTLT-2604.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
