### ISSUE TITLE
Addition of user of type admin when using template

### ISSUE THREAD

**Issue by curtkersey** [F5Networks/f5-google-gdm-templates#65]
## Do you already have an issue opened with F5 support?
No.

## Description
I deployed in GCP using template v3.11.1 with f5-existing-stack-same-net-cluster-byol-3nic-bigip, and I see a user of type admin (in addition to the admin user) be created. In my most recent run it was user 83026c62dd719aa734bf.  What function does this user serve?

## Template
f5-existing-stack-same-net-cluster-byol-3nic-bigip

## Severity Level
2 - causing an issue with customer that is deploying - need to know why this additional user is being created.

**Comment by shyawnkarim** [comment]
An additional user is created to do the clustering, however, it should be deleted after it finishes. I've filed a bug, internal ID ESECLDTPLT-2627, for engineering to review.

Since this is a sev2, can you have an SR opened so that we can get access to the logs as well?

**Comment by curtkersey** [comment]
Thanks for the information.  Support case created - C3577039; QKVIEW uploaded.  Let me know if you need anything else.

**Comment by shyawnkarim** [comment]
Thank you. I've added the SR info to our bug ticket.

**Comment by shyawnkarim** [comment]
Closing. This issue was resolved with [Release 3.12.0](https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v3.12.0).
