### ISSUE TITLE
qkview trapped a global exception

### ISSUE THREAD

**Issue by leondelyon3** [F5Networks/f5-google-gdm-templates#67]
## Do you already have an issue opened with F5 support?
NO

## Description
It is not possible to generate qkview file with the –progress-bar option because of the following error:
Trapped a global exception!
Schema item diags_ihealth_request.qkview_progress (tag 31600) not found

## Template
v3.12
Either:
https://github.com/F5Networks/f5-google-gdm-templates/tree/main/supported/failover/same-net/via-api/3nic/existing-stack/payg

Or:
https://github.com/F5Networks/f5-google-gdm-templates/tree/main/supported/failover/same-net/via-lb/3nic/existing-stack/payg

## Severity Level

Severity:  5

**Comment by shyawnkarim** [comment]
Thanks for reporting this issue. We are now tracking it internally with ID ESECLDTPLT-2716.

**Comment by shyawnkarim** [comment]
Closing due to age. These legacy templates are now in maintenance mode and are being replaced by our next-generation templates available in the [Cloud Templates 2.0 GitHub repo](https://github.com/F5Networks/f5-google-gdm-templates-v2).
