### ISSUE TITLE
Requesting shared VPC support

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#69]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Currently the templates operate in one customer's VPC but do NOT understand the concept of host and shared VPC. Requesting support for shared vpc.

Reference: https://cloud.google.com/vpc/docs/shared-vpc

## Template
All tempaltes

## Severity Level
3

**Comment by shyawnkarim** [comment]
We actually implemented this in [Release 3.6.0](https://github.com/F5Networks/f5-google-gdm-templates/releases/tag/v3.6.0) and can be seen in [here in this template](https://github.com/F5Networks/f5-google-gdm-templates/blob/00c8a4e46957c6183e0cf70d06bf326f9ec4d270/supported/failover/same-net/via-api/3nic/existing-stack/payg/f5-existing-stack-same-net-cluster-payg-3nic-bigip.yaml#L37).

**Comment by shyawnkarim** [comment]
Closing. Please open another issue if needed.
