### ISSUE TITLE
GCP 15.1.3 OS upgrade issue

### ISSUE THREAD

**Issue by vividcolor12** [F5Networks/f5-google-gdm-templates#70]
## Do you already have an issue opened with F5 support?
Github Issues are consistently monitored by F5 staff, but should be considered as best effort only and you should not expect to receive the same level of response as provided by F5 Support. Please [open an case](https://support.f5.com/csp/article/K2633) with F5 if this is a critical issue.

## Description
Describe the problem you're having or the enhancement you'd like to request.

https://cdn.f5.com/product/bugtracker/ID960749.html
GCP was established as 15.1.2.1.
However, there is currently a DNS resolver issue in 15.1.2.1, so we are upgrading to 15.1.3.

After installation, there is a problem with the device trust. Even if you fail over, Alias IP does not move to Active equipment.

## Template
For bugs, enter the template with which you are experiencing issues below.
https://cdn.f5.com/product/bugtracker/ID960749.html

## Severity Level
For bugs, enter the bug severity level. Do not set any labels.

Severity: <Fill in level: 1 through 5>
Severity 2 (High)
Severity level definitions:
 1. **Severity 1 (Critical)** : Defect is causing systems to be offline and/or nonfunctional. immediate attention is required.
 2. **Severity 2 (High)** : Defect is causing major obstruction of system operations.
 3. **Severity 3 (Medium)** : Defect is causing intermittent errors in system operations.
 4. **Severity 4 (Low)** : Defect is causing infrequent interuptions in system operations.
 5. **Severity 5 (Trival)** : Defect is not causing any interuptions to system operations, but none-the-less is a bug.

**Comment by shyawnkarim** [comment]
Since this a Sev2 can you please create a support ticket with F5?

**Comment by shyawnkarim** [comment]
Closing. Please reopen if needed.
