### ISSUE TITLE
2nicByol Disk problem

### ISSUE THREAD

**Issue by ofaruk89** [F5Networks/f5-google-gdm-templates#76]
Hi,

when i deploy 1 boot byol image (16.1  or 15.4)  , it provision auto 54G disk, and i see in f5 max 20G  available for modules. Recommended disk space is for avr + asm = 36G 

**My yaml file for modules-> bigIpModules**: ltm:nominal,asm:nominal,avr:nominal,fps:nominal
**i am seperating with comma** (yaml file guide says : ## (OPTIONAL) Enter a comma-separated list of modules and provisioning level, for example 'ltm:nominal' or 'ltm:nominal,asm:nominal'.)   

**PS**(when i update repo it says me use hypen between module names , is this problem fixed ? )

**Comment by ofaruk89** [comment]
And another issue : management work as app int ,  app int work as management interface

**Comment by shyawnkarim** [comment]
Previous version fo our templates erroneously said that the modules needed to be comma separated. The latest version says that they need to be hyphen separated. 

For your second issue, I just launched the template and app traffic was assigned to nic0 and mgmt traffice was assigned to nic1. This is the correct behavior.

**Comment by shyawnkarim** [comment]
Closing.

Please reopen another issue if you would like additional help.
