### ISSUE TITLE
experimental HA prod template will not provision - failed dependencies

### ISSUE THREAD

**Issue by JeffGiroux** [F5Networks/f5-google-gdm-templates#9]
Deploying experimental HA prod template, but will no provision.
https://github.com/F5Networks/f5-google-gdm-templates/tree/master/experimental/failover/same-net/via-api/3nic/production-stack/byol

Checked /var/log/cloud/google directory and only see install.log. It's just looping on "waiting for cloud libs install to complete"

Prior to that, some other logs of relevance in install.log...

mcpd ready
loading verifyHash script
waiting for cloud libs install to complete
waiting for cloud libs install to complete
waiting for cloud libs install to complete
Loading configuration...
 /config/verifyHash
loaded verifyHash
verifying /config/cloud/f5-cloud-libs.tar.gz
script did not successfully complete, status:1
/config/cloud/f5-cloud-libs.tar.gz is not valid
waiting for cloud libs install to complete
waiting for cloud libs install to complete
waiting for cloud libs install to complete
...and more and more

**Comment by jsevedge** [comment]
We are tracking this internally via ID 630.

**Comment by jsevedge** [comment]
This issue is resolved in v1.5.1.

Keep in mind that outbound access is required, so similar errors to the above may still show up if the deployment is unable to download external dependencies from the internet.
